---
title: "MPG analysis"
author: "Alex Fennell"
date: "3/25/2022"
output: pdf_document
header-includes:
    - \usepackage{dcolumn}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r libraries,message=FALSE,warning=FALSE,appendix=TRUE}
library(ggplot2)
library(plyr)
library(dplyr)
library(gridExtra)
library(GGally)
library(stargazer)

```

```{r initial data examination,eval=TRUE,echo=FALSE,appendix=TRUE}
mtdat<-mtcars
```

Based on this output, it appears that many numeric variables need to be converted
to factors especially the am variable since that is of particular interest

```{r converting variables to factors,appendix=TRUE}
mtdat$cyl<-factor(mtcars$cyl)
mtdat$vs<-factor(mtcars$vs,labels=c("V-Shaped","Straight"))
mtdat$am<-factor(mtcars$am,labels=c("Automatic","Manual"))
mtdat$gear<-factor(mtcars$gear)
mtdat$carb<-factor(mtcars$carb)
```
# Exploratory Data Analysis summary

Now lets look at a summary of the data
```{r summary of data,eval=TRUE}
summary(mtdat)
```

## Boxplots of the data

```{r boxplots,appendix=TRUE,eval=FALSE}
b1<-ggplot(mtdat,aes(y=mpg,x=am))+
    geom_boxplot()+
    xlab("Transmission Type")+
    ylab("Miles Per Gallon (MPG)")+
    ggtitle("MPG for Automatic vs. \n Manual Cars")+
    theme(plot.title=element_text(hjust=.5))

b2<-ggplot(data=mtdat,aes(y=mpg,x=am,fill=cyl))+
    geom_boxplot()+
    xlab("Transmission Type")+
    ylab("Miles Per Gallon (MPG)")+
    ggtitle("MPG for Automatic vs. Manual Cars \n as a Function of Cylinders")+
    theme(plot.title=element_text(hjust=.5))+
    guides(fill=guide_legend(title="Cylinders"))

b3<-ggplot(data=mtdat,aes(y=mpg,x=am,fill=gear))+
    geom_boxplot()+
    xlab("Transmission Type")+
    ylab("Miles Per Gallon (MPG)")+
    ggtitle("MPG for Automatic vs. Manual Cars \n as a Function of Gears")+
    theme(plot.title=element_text(hjust=.5))

b4<-ggplot(data=mtdat,aes(y=mpg,x=am,fill=vs))+
    geom_boxplot()+
    xlab("Transmission Type")+
    ylab("Miles Per Gallon (MPG)")+
    ggtitle("MPG for Automatic vs. Manual Cars \n as a Function of Cylinders")+
    theme(plot.title=element_text(hjust=.5))+
    guides(fill=guide_legend(title="Engine"))

grid.arrange(b1,b2,b3,b4,nrow=2)
```

## Correlation plots

```{r pairs plot numeric variables,eval=FALSE,message=FALSE,appendix=TRUE}
mtdat%>%
    select_if(is.numeric)%>%
    ggpairs(.)
```

## Modeling analysis
```{r linear models,eval=TRUE}
fit1<-lm(mpg~am,data=mtdat)
```

### Model fit
```{r model diagnostics,appendix=TRUE,eval=FALSE, fig.show="hold", out.width="50%"}
par(mfrow=c(2,2))
plot(fit1)
```

```{r model comparisons,eval=TRUE}
fit2<-update(fit1,mpg~am+cyl+vs)
fit3<-update(fit1,mpg~am++cyl+vs+wt+hp)
anova(fit1,fit2,fit3)
```



```{r model comparison table, results='asis',message=FALSE}
# Create nested regression model table
stargazer(fit1,fit2,fit3,type='latex',header=FALSE,single.row = TRUE,
          title="MPG Regression Model Results")
```

# Appendix
```{r, ref.label = knitr::all_labels(appendix == TRUE),echo=TRUE,eval=TRUE,warning=FALSE,message=FALSE,fig.dim=c(6.5,5)}

```